version: '3.7'
services:
  local_driver:
    container_name: smpc_local_driver
    image: smpc_local_driver:latest
    build:
      context: ./
    env_file:
      - .env.production
    volumes:
      - ./certs:/smpc-local-driver/certs
    ports:
      - 3002:3002
    networks:
      - local_driver

networks:
  local_driver:
    name: smpc_local_driver
